public class asciiart
{
	public static void main(String args[])
	{
		
		System.out.println("                              ()_");
		System.out.println("                              || `-._.-.");
		System.out.println("                              ||_    .'");
		System.out.println("                              || `-.'");
		System.out.println("         +                    ||                    +");
		System.out.println("         |                    ||                    |");
		System.out.println("        / \\\\               _,,.||.__                / \\\\");
		System.out.println("       /___\\\\           ,-'         `-.            /___\\\\");
		System.out.println("     ______|===|_________,'               `.__________|===|______");
		System.out.println("    /      |===|        /                   \\\\         |===|      \\\\");
		System.out.println("   /___________________/                     \\\\____________________\\\\");
		System.out.println("   |  +-----+ +-----+  |`-._              _.-'|  +-----+ +-----+  |");
		System.out.println("   |  ||_|_|| ||_|_||  | |. `'----------'' .| |  ||_|_|| ||_|_||  |");
		System.out.println("   |  ||_|_|| ||_|_||  | |:  | ||    :| |  :| |  ||_|_|| ||_|_||  |");
		System.out.println("---| %%---%%+ +%%%--+  | |:__| ||____:| |__:| |  +-%%%-+ %%---%%% |---");
		System.out.println("   |%%%%_%%%%_%%%%%____| |/  | || -  :| |  \\\\| |___%%%%%_%%%%_%%%%%|");
		System.out.println("     `|   %|   `|'   |`.`-._ | |'    `| |__.-'.'|  %|'   `|   %|MJP");
		System.out.println("                 |`.`-._``---....---''_.-'.'|");
		System.out.println("                 `. `-._``---....---''_.-' .'");
		System.out.println("                   `.   ``---....---''   .'");
		System.out.println("                     `.                .'");
		System.out.println("                       `.            .'");
		System.out.println("                         `.        .'");
		System.out.println("                          ().    .()");
		System.out.println("/\\\\_/\\\\_/\\\\_/\\\\_/\\\\_/\\\\_/\\\\_/\\\\_/\\\\_/\\\\_||:    :||_/\\\\_/\\\\_/\\\\_/\\\\_/\\\\_/\\\\_/\\\\_/\\\\_/\\\\_/\\\\");
		System.out.println("||=||=||=||=||=||=||=||=||=||=||:    :||=||=||=||=||=||=||=||=||=||=||");
		System.out.println("\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"      \\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"\\\"");
		System.out.println("The White House");
		System.out.println("");
		System.out.println("");
		System.out.println("        ");
		System.out.println("                 ++  ~?????I                :$O                         ");
		System.out.println("    ????????$?$?O  ?  ???        $$$$$$$$$$$$$$$$$$$$$$$$$$8            ");
		System.out.println("      ?+.8????????   ?    ?        $$:8$$$$$$$$$$$$$$$$$$$$$$ $7            ");
		System.out.println("      ??????????????        ?? $$$$$$$$$$$$$$$$$$$$$$$$$O  .           ");
		System.out.println("      ???????I????            $$$$$$$$$+$$$$$$$$$$$$$$$$$               ");
		System.out.println("     ??????????             ??.   8$$$$$ $$$$$$$$$$$$$.$  :             ");
		System.out.println("      ???????               ??$$$ $  $$$$$$$$$$$$$$$$$$                 ");
		System.out.println("      .??                  ???$$$$$$$.$$8$OO$$$$$$$$$$$8                ");
		System.out.println("        ???   ?+          +???$$$$$$$$ $$$   $$$  $$?                   ");
		System.out.println("           ?  ~ D         +???$$$$$$$$$       $     $   ~               ");
		System.out.println("             ?????+         Z$ $$$$$$$$$     O    $D  +8                ");
		System.out.println("            ??????+?            $$$$$$$            . 8$   $I            ");
		System.out.println("             ?????????          $$$$$$                O$    $$ +        ");
		System.out.println("             +???????~          $$$$$$O Z               ?$$ $    O      ");
		System.out.println("   Western     ??????            $$$$  $              $$$$$$$$          ");
		System.out.println("    Nation     ????Z             $$$Z                 $$$$$$$$          ");
		System.out.println("               ???                    Eastern             $$$  =      ");
		System.out.println("                ?                     Nation                 '        ");
		System.out.println("                ?                                                   ");
		System.out.println("Different Nations");
		System.out.println("");
		System.out.println("");
		System.out.println(":::::::::::::::::D::::::::::::::::8DI:::::::::::::::::::::::::::::::::::::::");
		System.out.println("::::::::::::::::IZ:::::::::::::::DD:::::::::::::::::::::::::::::::::::::::::");
		System.out.println("::::::::::::::::8:::::::::::::::DN::::::::::::::::::::::::::::::::::::::::::");
		System.out.println("::::::::::::::::D::::::::::::::ZD::::::::::::::::::$DDDDDDDDDDDDDD8?::::::::");
		System.out.println("::::::::::::::::D:::::::::::::=D::::::::::::::+DDDDNZ::::::::::::~ODDDNDDD::");
		System.out.println("::::::::::::::::D:::::::::::::DD:::::::::::~DDD:::::::::::::::::::::::::$DDD");
		System.out.println("::::::::::::::::D::::::::::::8D::::::::::=D$::::::::::::::::::::::::::::::::");
		System.out.println("::::::::::::::::Z$:::::::::::D?::::::$MMMMD=::::::::::::::::::::::::::::::::");
		System.out.println(":::::::::::::::::D:::::::::::D::~MMMMMMMMMMMMMMM::::::::::::::::::::::::::::");
		System.out.println(":::::::::::::::::D:::::::::::DNMMMMMMMMMMMMMMMMMMM::::::::::::::::::::::::::");
		System.out.println(":::::::::::::::::Z+:::::::::~MMMMMMMMM   MMMMMMMMMMM::::::::::::::::::::::::");
		System.out.println("::::::::::::::::::D::::::::NMMMMMMMM.      M MMMMMMMMDDZ::::::::::::::::::::");
		System.out.println("Z:::::::::::::::::DZ::::::MMMMMMMMMM       M MMMMMMMMM::::DD$:::::::::::::::");
		System.out.println("DD:::::::::::::::::D~::::+MMMMMMMMMM       M MMMMMMMMMM::::::8D8::::::::::::");
		System.out.println(":8D:::::::::::::::::D::::MMMMMMMMMMM      ?+ MMMMMMMMMMM::::::::DD::::::::::");
		System.out.println("::?D:::::::::::::::::D::8MMMMMMMMMMMO     M .7MMMMMMMMMM::::::::::DD?:::::::");
		System.out.println("::::D=::::::::::::::::D+MMMMMMMMMMMM     MM   . MMMMMMMM::::::::::::DD~:::::");
		System.out.println(":::::7D:::::::::::::::::MMMMMMMMMM        MM   .MMMMMMMM~::::::::::::?DD::::");
		System.out.println(":::::::8D:::::::::::::::MMMMMMMM,              =MMMMMMMM:::::::::::::::DD8::");
		System.out.println(":::::::::D8:::::::::::::MMMMMMM?               MMMMMMMMMD:::::::::::::::DDD:");
		System.out.println(":::::::::::DD::::::::::::MMMMMMD               MMMMMMMMM:D:::::::::::::::ZDD");
		System.out.println(":::::::::::::OD8:::::::::NMMMMMM .              MMMMMMM:::D:::::::::::::::DD");
		System.out.println("::::::::::::::::8D8:::::::MMMMMM$              .MMMMMMI:::8Z:::::::::::::::D");
		System.out.println(":::::::::::::::::::ZDDZ::::MMMMMM              .MMMMMO:::::D::::::::::::::::");
		System.out.println("::::::::::::::::::::::::::+IMMMMMM               MMM+::::::ID:::::::::::::::");
		System.out.println("::::::::::::::::::::::::::::::MMMM .             MD:::::::::D:::::::::::::::");
		System.out.println("::::::::::::::::::::::::::::::::MM.          . .?8::::::::::8:::::::::::::::");
		System.out.println(":::::::::::::::::::::::::::::::::::: . .     :::=::::::::::::I::::::::::::::");
		System.out.println("::::::::::::::::::::::::::::::::::::I:::::::::::N::::::::::::O::::::::::::::");
		System.out.println("::::::::::::::::::::::::::::::::::+O::::::::::::~::::::::::::D::::::::::::::");
		System.out.println("::::::::::::::::::::::::::::::::ID:::::::::::::D:::::::::::::D::::::::::::::");
		System.out.println("::::::::::::::::::::::::::::::DD::::::::::::::D::::::::::::::O::::::::::::::");
		System.out.println("Starting Screen");
		System.out.println("");
		System.out.println("");
		System.out.println("                      .  NMMMMMMMM+ +MMMMMMMMN...                       ");
		System.out.println("                      .ZMMMMMMMMMMMMMMMMMMMMMMM$.                       ");
		System.out.println("                      MMMMMMMMMMMMMMMMMMMMMMMMMMM.                      ");
		System.out.println("                   . +MNMMMMMMMMMMMMMMMMMMMMMMMMM=..                    ");
		System.out.println("              ...  . MMMMMMMMMMMMMMMMMMMMMMMMMMMMN..   .  .             ");
		System.out.println("            .  .+DMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMD+...             ");
		System.out.println("         ...8MNMMMMMMIMNMMMMMMMMMMMMMMMMMMMMMMMMM?MMMMMMMMZ ,..         ");
		System.out.println("         .8MMMMMMMMMMD$MMMMMMMMMMMMMMMMMMMMMMMMMZNMMMMMMMMMN8           ");
		System.out.println("      ..7MMMMMMMMMMMMMM,MMMMMMMMMMMMMMMMMMNMMMM,MMMMMMMMMMMMMMI .       ");
		System.out.println("       .MMMMMMMMMMMMMMMMM+:DMMMMMMMMMMMMMMMN:=MMNMMMMMMMMMMMMMM         ");
		System.out.println("         ZMMMMMMMMMMMMMMMMMMN?.. ,~=~,. .?MMMMMMMMMMMMMMMMMMM$          ");
		System.out.println("         . MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM  .         ");
		System.out.println("            . +NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN+ .            ");
		System.out.println("            ...     ,ZNMMMMMMMMMMMMMMMMMMMMMMMMMD$, ..                  ");
		System.out.println("            .  .. . .  .. .   .,::~~~::,..  ....    . .                 ");
		System.out.println("                      . +OMMMMMN.   ..,DMMMMM8?                         ");
		System.out.println("                      ZMMMMMMMMMMMMMMMMMMMMMMMMM$                       ");
		System.out.println("                      .DMMMMMMMMMM . MMMMMMMMMMD.                       ");
		System.out.println("                      .IMMMMMMMMMM...MMMMMMMMMM?                        ");
		System.out.println("                      . OMMMMMMM$ ..  $MMMMMMMZ.                        ");
		System.out.println("                      ..  . .... .  .  . . . . .,                           ");
		System.out.println("                                                                            ");
		System.out.println("");
		System.out.println("");
		System.out.println("   .  ................. .            .   .             ................  . .");
		System.out.println("   =MMMMMMMMMMMMMMMMMMMMM.            MMM.           .MMMMMMMMMMMMMMMMMMMMM~");
		System.out.println(".~MMMMMMMMMMMMMMMMMMMMMMMN~  .      . NMM           ~MMMMMMMMMMMMMMMMMMMMMMM");
		System.out.println("?MMMMMMMMMMMMMMMMMMMMMMMMMM. .       .MMM..        ,MMMMMMMMMMMMMMMMMMMMMMMM");
		System.out.println("MMMMMMMMMMMMMMMMMMMMMMMMMMMM         .MMM.     . . MMMMMMMMMMMMMMMMMMMMMMMMM");
		System.out.println("MMMMMMMMMMMMMMMMMMMMMMMMMMMMM.        MMM..   .  .MMMMMMMMMMMMMMMMMMMMMMMMMM");
		System.out.println("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM. .   .~MMM~.   . .MMMMMMMMMMMMMMMMMMMMMMMMMMM");
		System.out.println("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM$.    .OMMMZ    . $MMMMMMMMMMMMMMMMMMMMMMMMMMM");
		System.out.println("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMD..  .MMMMM .  .NMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
		System.out.println("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM . :MMMMM,   MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
		System.out.println("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM,. $MMMMM7. ,MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
		System.out.println("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN+.MMMMMMM.+MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
		System.out.println("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM$MMMMMMMZMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
		System.out.println("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
		System.out.println("The Spy");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("       _______________________________________________________________________________");
		System.out.println("     .'  ___________________________________________________________________________  '.");
		System.out.println("     : .'                                                                           '. :");
		System.out.println("     | |      _________________________________________________________________      | |");
		System.out.println("     | |    .:_________________________________________________________________:.    | |");
		System.out.println("     | |    |                                                                   |    | |");
		System.out.println("     | |    |Two spies want to get in an enemy's military base. A soldier walks |    | |");
		System.out.println("     | |    |up to the guard, and the guard says,6, and the soldier says,\"3\".   |    | |");
		System.out.println("     | |    |The guard lets the soldier through. Another soldier walks up to the|    | |");
		System.out.println("     | |    |guard, and the guard says,12, and the soldier says,6. The          |    | |");
		System.out.println("     | |    |guard lets the soldier through. One of the spies jumps down from   |    | |");
		System.out.println("     | |    |out of the tree, walks up to the guard, and the guard says, 8,     |    | |");
		System.out.println("     | |    |and the spy says,4. The guard then shoots the spy and the spy      |    | |");
		System.out.println("     | |    |dies.                                                              |    | |");
		System.out.println("     | |    |                    What should the spy have said?                 |    | |");
		System.out.println("     | |    |                                                                   |    | |");
		System.out.println("     | |    |          Password - __________________________                    |    | |");
		System.out.println("     | |    |                    |  |  |  |  |  |  |  |  |  |                   |    | |");
		System.out.println("     | |    '.___________________|__|__|__|__|__|__|__|__|__|__________________.'    | |");
		System.out.println("     | |                                                                             | |");
		System.out.println("     | |                                     iMac                                    | |");
		System.out.println("     : '.___________________________________________________________________________.' :");
		System.out.println("      \"._____________________________________\\__/____________________________________.\"");
		System.out.println("                                              ||");
		System.out.println("                                              || ");
		System.out.println("");
	}
}
